---
variables:
  PYTHON_VERSION: "3.9"
  PIPENV_VENV_IN_PROJECT: "1"

stages:
  - init
  - test
  - deploy

pipenv-creator:
  stage: init
  tags:
    - docker
  image: aminkm/linter:latest
  script:
    - pipenv --python 3.9 install --dev
  cache:
    paths:
      - .venv
    key: $CI_COMMIT_REF_NAME-$PYTHON_VERSION
    untracked: true
    policy: pull-push
  interruptible: true


pylint:
  stage: test
  tags:
    - docker
  image: aminkm/linter:latest
  before_script:
    - mkdir -p public/badges public/lint
    - echo undefined > public/badges/$CI_JOB_NAME.score
    - pip install pylint-exit
  script:
    - pylint --exit-zero --output-format=text $(find -type f -name "*.py" ! -path "**/.venv/**") | tee /tmp/pylint.txt
    - sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' /tmp/pylint.txt > public/badges/$CI_JOB_NAME.score
    - pylint --exit-zero --output-format=pylint_gitlab.GitlabPagesHtmlReporter $(find -type f -name "*.py" ! -path "**/.venv/**") > public/lint/index.html
  after_script:
    - anybadge --overwrite --label $CI_JOB_NAME --value=$(cat public/badges/$CI_JOB_NAME.score) --file=public/badges/$CI_JOB_NAME.svg 4=red 6=orange 8=yellow 10=green
    - |
      echo "Your score is: $(cat public/badges/$CI_JOB_NAME.score)"
    - anybadge --label=pipeline --value=passing --file=public/badges/pipeline.svg passing=green failing=red
  artifacts:
    paths:
      - public


black:
  stage: test
  tags:
    - docker
  image: aminkm/linter:latest
  script:
    - black .


isort:
  stage: test
  tags:
    - docker
  image: aminkm/linter:latest
  script:
    - isort .


pages:
  stage: deploy
  tags:
    - docker
  image: aminkm/linter:latest
  script:
    - echo
  artifacts:
    paths:
      - public
